CREATE TABLE  IF NOT EXISTS `I80Davis` (
  `date` text NOT NULL,
  `time` text NOT NULL,
  `station_id` double NOT NULL,
  `col3` double DEFAULT NULL,
  `col4` double DEFAULT NULL,
  `col5` double DEFAULT NULL,
  `col6` double DEFAULT NULL,
  `col7` double DEFAULT NULL,
  `col8` double DEFAULT NULL,
  `col9` double DEFAULT NULL,
  `col10` double DEFAULT NULL,
  `col11` double DEFAULT NULL,
  `col12` double DEFAULT NULL,
  `col13` double DEFAULT NULL,
  `col14` double DEFAULT NULL,
  `col15` double DEFAULT NULL,
  `col16` double DEFAULT NULL,
  `col17` double DEFAULT NULL,
  `col18` double DEFAULT NULL,
  `col19` double DEFAULT NULL,
  `col20` double DEFAULT NULL,
  `col21` double DEFAULT NULL,
  `col22` double DEFAULT NULL,
  `col23` double DEFAULT NULL,
  `col24` double DEFAULT NULL,
  `col25` double DEFAULT NULL,
  `col26` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `I80Stations` 
( 
    `ID` INT NOT NULL,
    `Fwy` INT NOT NULL,
    `Dir` TEXT NOT NULL,
    `District` INT NOT NULL,
    `County` INT NOT NULL,
    `City` INT DEFAULT NULL,
    `State_PM` DOUBLE NOT NULL,
    `Abs_PM` DOUBLE NOT NULL,
    `Latitude` DOUBLE NOT NULL,
    `Longitude` DOUBLE NOT NULL,
    `Length` DOUBLE DEFAULT NULL,
    `Type` TEXT NOT NULL,
    `Lanes` INT NOT NULL,
    `Name` TEXT NOT NULL,
    `User_ID_1` TEXT DEFAULT NULL,
    `User_ID_2` TEXT DEFAULT NULL,
    `User_ID_3` TEXT DEFAULT NULL,
    `User_ID_4` TEXT DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;